SQL_08.md
ykgoesdumb/TIL pull request #14
Opened 2023-03-12 08:32 UTC by Leo-hs-lee

## Objectives
Try to measure how many days it takes to finish this note (10 problem)

## Describe Your Change
20, 21, 22 finished for day 1

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Study Summary
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## References

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
빈 부분 추가 커밋까지 완료 되면 Merge 하시는걸로 하시죠

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-12 08:42 UTC, ykgoesdumb commented on SQL/SQL_08.md
> +# Your code
ditto

2023-03-18 18:05 UTC, ykgoesdumb requested changes

2023-03-18 18:05 UTC, ykgoesdumb commented on .DS_Store
의미 없는 binary 파일입니다 .gitignore 에 이 파일의 path 추가하시고 .gitignore 업데이트 해주세요

2023-03-29 05:09 UTC, ykgoesdumb commented
밑에 .gitignore 파일에  conflict 가 났네요 이는 현재 이 branch 를 분기한 시점 뒤에  master branch 에서 제가 .gitignore 파일을 수정,반영 했기 때문에 master branch 로 merge 를 시도할때 충돌이 나고있습니다. 아래를 참조하셔서 conflict 해결해주세요

https://docs.github.com/ko/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2023-04-01 23:37 UTC, Leo-hs-lee commented
> 밑에 .gitignore 파일에 conflict 가 났네요 이는 현재 이 branch 를 분기한 시점 뒤에 main branch 에서 제가 .gitignore 파일을 수정,반영 했기 때문에 main branch 로 merge 를 시도할때 충돌이 나고있습니다. 아래를 참조하셔서 conflict 해결해주세요
> 
> https://docs.github.com/ko/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2023-04-02 10:01 UTC, ykgoesdumb approved these changes
LGTM

2023-04-02 10:01 UTC, merged